#!/bin/sh
# Convert text files to strings in a JavaScript object

echo "var textfiles = {"

for file in "$@"
do
	echo -n '"'$file'": "'
	tr -d '\r' <"$file" | sed -E 's/"/\\"/g' | sed -E ':a;N;$!ba;s/\n/\\n/g' | tr -d '\n'
	echo '",'
done

echo "};"
